######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 2 16:12:51 2009
######################################################################

TEMPLATE = app
CONFIG += qt debug
TARGET = tests
DEPENDPATH += .
INCLUDEPATH += .
OBJECTS_DIR = ./obj
MOC_DIR = ./moc

# Input
HEADERS += ../Board.h \
           ../datastructs.h \
           ../Dict.h \
           ../TileRepo.h \
           ../TurnInfo.h \
           ../globals.h
SOURCES += ../Board.cpp \
           ../Dict.cpp \
           ../TileRepo.cpp \
           ../TurnInfo.cpp \ 
           tests.cpp
